# Generated by Django 6.0.7 on 2026-08-09 23:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sign_name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('sign_category', models.CharField(choices=[('word', 'Word'), ('sign', 'Sign'), ('representation', 'Representation')], default='sign', max_length=50, null=True)),
                ('is_active', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'signs',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word_name', models.CharField(max_length=50)),
                ('grammatical_category', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection'), ('determiner', 'Determiner'), ('article', 'Article'), ('numeral', 'Numeral')], default='verb', max_length=50, null=True)),
                ('use_level', models.CharField(choices=[('colloquial', 'Colloquial'), ('informal', 'Informal'), ('neutral', 'Neutral'), ('formal', 'Formal'), ('technical', 'Technical'), ('scientific', 'Scientific'), ('literary', 'Literary'), ('slang', 'Slang'), ('archaic', 'Archaic')], default='neutral', max_length=30, null=True)),
                ('description', models.TextField(null=True)),
                ('is_active', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'words',
            },
        ),
    ]
