# Generated by Django 4.2.30 on 2026-08-15 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('extension', models.CharField(choices=[('img', 'img'), ('png', 'png')], default='img', max_length=20)),
                ('url', models.TextField()),
                ('is_primary', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representationsby', to=settings.AUTH_USER_MODEL)),
                ('sign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idsigns', to='dictionary.sign')),
            ],
            options={
                'db_table': 'sign_representation',
            },
        ),
    ]
